name: Deploy to Heroku

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update merged_data.csv
      run: |
        python merged_data.py # This script updates your merged_data.csv

    - name: Commit updated merged_data.csv
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add merged_data.csv
        git commit -m "Update merged_data.csv"

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/dfs-odds-extension.git HEAD:main
