name: Update Data

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set this to your required Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements.txt
    - name: Run pp_mlb.py
      run: python pp_mlb.py
    - name: Stash changes
      run: git stash
    - name: Pull changes from the remote repository
      run: git pull --rebase
    - name: Commit and push if there are changes
      run: |
        git config user.email "dhiren3102@gmail.com"
        git config user.name "DhirenShivdasani"
        git add .
        git commit -m "Automated data update" -a || exit 0  # '-a' to include all changes
        git push origin main
    - name: Trigger deploy workflow
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.MLB_TOKEN }}" \
        https://api.github.com/repos/DhirenShivdasani/mlb/dispatches \
        -d '{"event_type":"deploy-heroku"}'
