name: Update Data

on:
  push:
    branches:
      - main
    paths:
      - 'mlb_props.py'
      - 'requirements.txt'
      - '.github/workflows/update_data.yml'  # Only run when these files change
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set this to your required Python version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements.txt
    
    - name: Run mlb_props.py
      run: python mlb_props.py
    
    - name: Pull changes from the remote repository
      run: |
        git pull --rebase origin main || echo "No changes to pull"
    
    - name: Commit and push if there are changes
      run: |
        git config user.email "dhiren3102@gmail.com"
        git config user.name "DhirenShivdasani"
        git add .
        git commit -m "Automated data update" -a || echo "No changes to commit"
        git push https://${{ secrets.MLB_SECRET }}@github.com/DhirenShivdasani/mlb.git main || echo "No changes to push"
